### ISSUE TITLE
Confusing GCC_INSTALL_PREFIX

### ISSUE THREAD

**Issue by hamsteri15** [BobSteagall/gcc-builder#7]
I have gcc-builder placed in /u2/pjppetteri/Installations/gcc-builder.

In gcc-build-vars.sh I set:

export GCC_INSTALL_PREFIX=/u2/pjppetteri/compilers/gcc/11.3.0

when trying to compile gcc-11.3.0 but somehow my gcc gets installed in to path:
/u2/pjppetteri/Installations/gcc-builder/dist/u2/pjppetteri/compilers/gcc/11.3.0

Is this intentional? Is the first '/' in GCC_INSTALL_PREFIX always removed and the GCC_INSTALL_PREFIX should be put relative to the path I execute the scripts from?

**Comment by BobSteagall** [comment]
What is the exact sequence of commands that you ran to do the build, stage, pack, and install steps?

**Comment by hamsteri15** [comment]
Nevermind, I just noticed that there's an additional 'install-gcc-tarball.sh' -script which I forgot to run in step e. My mistake!
